### ISSUE TITLE
Load in file data into array

### ISSUE THREAD

**Issue by winterfrost28** [longtongj28/price-notifier#2]
Currently, when the user inputs a best buy url, certain parts of the JSON such as product name and price are saved to a text file. 

When the user starts the program, there should be a check to see if the file that contains the JSON exists.
If it does, then load the information into the program. If not, then create a blank file under the name of tracked_products.txt.
The information should be loaded into some sort of class or enumeration.

For example:
If the text file contains this -

name: ASUS - ROG Zephyrus 14� WQXGA 120Hz Gaming Laptop � AMD Ryzen 9� 16GB DDR5 Memory � AMD Radeon RX 6700S � 1TB PCIe 4.0 SSD
regularPrice: 1649.99
salePrice: 1649.99
lastPrice: 1649.99

name: ASUS - ROG Zephyrus 14� WQXGA 120Hz Gaming Laptop � AMD Ryzen 9� 16GB DDR5 Memory � AMD Radeon RX 6700S � 1TB PCIe 4.0 SSD
regularPrice: 1649.99
salePrice: 1649.99
lastPrice: 999.99

Then, it should load those two items into an array of "product" objects or something. In the future, users will be able to view products currently in their catalog. The lastPrice tag does not exist yet. but that should be apart of the product class.

**Comment by rafidini** [comment]
Hi @longtongj28,
you can use the `json` package for json files.

```python
import json

# Open file
fp = open(filename, 'r')

# Transform to JSON
array_products: list[dict] = json.load(fp)
```

### References
- [json](https://docs.python.org/3/library/json.html?highlight=json#module-json) — JSON encoder and decoder

**Comment by juanbasora** [comment]
I'll give this a try.

**Comment by winterfrost28** [comment]
Go ahead @juanbasora 💪
