### ISSUE TITLE
Graphical User Interface

### ISSUE THREAD

**Issue by winterfrost28** [longtongj28/price-notifier#5]
Currently, the program runs only on the terminal. Let's make the program more appealing by creating a simple user interface using some python GUI library that handles all of those inputs that the program is requesting.

Ideally, it should also have a settings button that allows the user to change their information on email. It should also have a catalog button that allows the user to view all of their saved products.

**Comment by Manny-op** [comment]
Hey, I would my hand at creating a GUI
